language: java
sudo: false

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.18.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

install: cd core && mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn test -B -Pintegrationtests -Dtest.browser=FIREFOX

jdk:
  - oraclejdk8

addons:
  firefox: latest